title: Itzel Schiaffini
catchphrase: Ready to bring ideas to the real world.
job: Industrial Design Carry
jobtitle: Industrial Designer
copyright: Copyright Â© 2018 - Itzel Schiaffini. All Rights Reserved.
thanks: Thanks for visiting my site!
picture: /assets/brand/profile.jpg

social:
  instagram: itzegomind
  email: itzegomind@gmail.com
  tumblr: itzegomind
  facebook: itzegomind
  pinterest: ischiaffini


# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

remote_theme: vectorvcinco/jekyll-portfolio

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      categories: "all"
